### ISSUE TITLE
Custom option support

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#110]
I noticed the custom option PR was recently merged, but even for the example in the pull request:

```
extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

message MyMessage {
  option (my_option) = "Hello world!";
}
```

I continue to get, `syntax error before: option` on `3.27.2`.

I'm going to keep digging but wanted to open this in case I missed something obvious about the new support.

**Comment by tomas-abrahamsson** [comment]
Oh, indeed, so appears. The [parser never accepts it.](https://github.com/tomas-abrahamsson/gpb/blob/3.27.2/src/gpb_parse.yrl#L144-L186). Let me know if you need assistance during your digging.

**Comment by tomas-abrahamsson** [comment]
I just pushed a minimal change to the parser, and a unit test for it. To a branch, custom-options. Would this be enough for your needs? At least, it parses the example. Handling of such options has been a low-prio area, though.

**Comment by tsloughter** [comment]
Seems to work for message options, yea. But what is weird is I have to use 

```
extend MessageOptions {
  optional string my_option = 51234;
}
```

instead of:

```
extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}
```

Which gives:

```
extend of unknown message .google.protobuf.MessageOptions

{error,
    {post_process,
        [{extend_ref_to_undefined_msg,
             ['.',google,'.',protobuf,'.','MessageOptions']}]}}
```

Did you have that issue?

Also, I wanted to use both message and field options. Field options still don't parse.

```
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  optional float my_field_option = 50002;
}

message MyMessage {
  optional int32 foo = 1 [(my_field_option) = 4.5];
}
```

**Comment by tomas-abrahamsson** [comment]
Regarding the first error,  do you use the option `use_packages`? 

I'll look into field options as well.

**Comment by tsloughter** [comment]
Woops, I was not. Sorry about that :). Worked fine with `use_packages`.

**Comment by tomas-abrahamsson** [comment]
I pushed another commit, for field options, to the coustom-options branch. If this is sufficient, we can go with that and I can eventually add parsing of more types of options later on?

**Comment by tsloughter** [comment]
Great! This is possibly all I need. I tried it out, using `to_msg_defs` since I want to do some special generation separate from protobuf encode/decode for options (though maybe there is another way I should do that? Currently it requires 2 passes, I do one to get the msg defs and then another that runs to completion to output the gpb generated modules).

But while I see the field option associated with the field, the message option isn't clear. For:

```
message MyMessage {
  option (my_option) = "Hello world!";
  string somefield = 1 [(my_field_option)=1.1];
}
```

I get:

```
     {{msg,'MyMessage'},
      [{field,somefield,1,2,string,optional,
              [{[my_field_option],1.1}]}]}
```

And do see `{option,[my_option],"Hello world!"},` also in the list that is the result from the `compile` but doesn't seem to be associated with the specific message.

**Comment by tomas-abrahamsson** [comment]
Hmm, yes, it was long ago, but I think the main reason then for lifting the `{option,[my_option],"Hello world!"}` was that I did not want to change the contents of the `{{msg,Name},Fields}` structure, mostly for backwards compatibility reasons. It was probably by mistake that it lost the association with the message. I think the easiest way forward is to add some top-level item, `{{msg_options, MsgName}, MsgOptions}` where `MsgOptions` is a list of message options, in the example only one element, `{[my_option], "Hello World!"}`. (and that  the top-level `{option,[my_option],"Hello world!"}` item is removed---I can hardly imagine it was used by anyone)

**Comment by tsloughter** [comment]
Yea, that'd work.

**Comment by tomas-abrahamsson** [comment]
Implemented now (the branch is updated)

**Comment by tsloughter** [comment]
Tried it. This is perfect, thanks!

**Comment by tomas-abrahamsson** [comment]
Merged, and included in 3.27.3 (closing)
